import { Roboto_Condensed } from 'next/font/google'
import './globals.css'
import { Metadata } from 'next'

const roboto_condensed = Roboto_Condensed({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto_condensed.className}>{children}</body>
    </html>
  )
}
